#!/bin/bash

# Fish
## Install fish
## if parameter is set
if [ "$1" = "install" ] || [ "$1" = "in" ]; then
	echo sudo zypper in fish
	echo chsh -s /usr/bin/fish `whoami`
fi

cd rest
## Add fzf to fish
./shell-fish-fzf

## Install oh-my-fish
./shell-fish-omf

## omf bang bang
./shell-fish-omf-bb

## Install fisher
./shell-fish-fisher

## fisher add z
./shell-fish-fisher-z
cd -
