#!/bin/bash

# Fish
## Install fish
## if parameter is set
if [ "$1" = "install" ] || [ "$1" = "in" ]; then
	echo sudo zypper in fish
	echo chsh -s /usr/bin/fish `whoami`
fi

## Add fzf to fish
rest/shell-fish-fzf

## Install oh-my-fish
rest/shell-fish-omf

## omf bang bang
rest/shell-fish-omf-bb
