#!/bin/bash

GIT_REPO_SPOTIFY=https://github.com/flanaras/opensuse-spotify-installer

# Add Arc-Flatabulous theme
# sudo zypper in gtk3-devel autoconf automake
# git clone https://github.com/andreisergiu98/arc-flatabulous-theme && cd arc-flatabulous-theme
# ./autogen.sh --prefix=/usr
# sudo make install

# Spotify
# https://github.com/flanaras/opensuse-spotify-installer
git clone $GIT_REPO_SPOTIFY
cd opensuse-spotify-installer
./install-spotify.sh
cd -
rm -rf opensuse-spotify-installer

