#!/bin/bash

version="Leap_15.0"
version="Tumbleweed"
tumbleweed="Tumbleweed"
version_tumbleweed_alt="openSUSE_Factory"

REPO_VLC=http://download.videolan.org/pub/vlc/SuSE/$version
REPO_MAVEN=http://download.opensuse.org/repositories/devel:/tools:/building/$version
packmanessentials=http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_$version/Essentials
mozilla=http://download.opensuse.org/repositories/mozilla/openSUSE_$version/
polybar=http://download.opensuse.org/repositories/home:/sysek/openSUSE_$version/

# Vlc
# echo "sudo zypper ar $REPO_VLC vlc"
# echo "sudo zypper mr -r vlc"
# echo "sudo zypper in vlc"

# Packman codecs
echo sudo zypper ar -cfp 90 $packmanessentials packman-essentials 
echo sudo zypper dup --from packman-essentials

# Mozilla
echo sudo zypper ar -cfp 90 $mozilla mozilla
echo sudo zypper dup --from mozilla

echo sudo zypper ar -cfp 99 $polybar polybar
echo sudo zypper in polybar

# Maven
# sudo zypper ar $REPO_MAVEN devel:tools:building
# sudo zypper mr -r devel:tools:building
# sudo zypper in maven
