#!/bin/bash

cmd=

##### ----- Personal touches ----- #####

# Install fish shell
cmd="$cmd fish"

# Pomodoro
# cmd="$cmd gnome-pomodoro"

# Vim setup
cmd="$cmd gvim"

# ripgrep
cmd="$cmd ripgrep"

## -- Media

# Equalizer
cmd="$cmd pulseaudio-equalizer"

# Pavucontrol
cmd="$cmd pavucontrol"

# A nice pdf viewer, I like more this than the default one
cmd="$cmd okular"

# KDE base is needed to load correctly the icons (I guess this could be done by installing the oxygen* icon pack and fonts)
# sudo zypper in -t pattern kde

# Image editor
cmd="$cmd gthumb"

# Keepassxc
cmd="$cmd keepassxc"

# Run application after inactivity
cmd="$cmd xautolock"

## -- Browsers

# Opera, for an alternative of firefox
cmd="$cmd opera"

## Other

# VM necessities
cmd="$cmd virtualbox"


##### ----- Work touches ----- #####

## -- Tools

# Dropbox
cmd="$cmd dropbox-cli"

# Windows remote connection
cmd="$cmd remmina"

# Mail Client (Thunderbird)
cmd="$cmd MozillaThunderbird"

# FileZilla
# cmd="$cmd filezilla"

# iostat
cmd="$cmd sysstat"

# terminal
cmd="$cmd rxvt-unicode"

# We love and need git
cmd="$cmd git"

# Xinput
cmd="$cmd xinput"

# Htop
cmd="$cmd htop"

# build tools
cmd="$cmd make patch autoconf automake cmake"
cmd="$cmd gcc gcc-c++"
cmd="$cmd tree"

# Java
## jdk8
cmd="$cmd java-1_8_0-openjdk-devel"

## jdk11
cmd="$cmd java-11-openjdk-devel"

# Tex and TexMaker can be necessary, although it is highly possible
# that more that the standard packages will be needed
# cmd="$cmd texlive"
# cmd="$cmd texmaker"
# cmd="$cmd texlive*" # Not the best solution but the easiest


# Tools missing for a kernel build
cmd="$cmd multipath-tools ncurses-devel"

##### ----- Convenience touches ----- #####
# Main menu editor is not installed by default
cmd="$cmd alacarte"

# Su on graphical applications (gnomesu)
cmd="$cmd libgnomesu"

# gnome-open
cmd="$cmd libgnome"

##### ----- Personalisation ----- #####
# i3 with dependencies 
cmd=`echo $cmd i3 \`rest/i3-dependencies\``

# Required fonts
cmd=`echo $cmd \`./packages-fonts\``

echo $cmd 

######## -------- Refresh and update packages -------- ########
