#!/bin/bash

packages=
keys=
temp=proprietary-binaries-temp

cd $temp

# Viber
FILENAME_VIBER=viber.rpm
rm $FILENAME_VIBER
DL_PACKAGE_VIBER=https://download.cdn.viber.com/desktop/Linux/$FILENAME_VIBER
#wget $DL_PACKAGE_VIBER
packages="$packages $FILENAME_VIBER"

# TeamViewer
FILENAME_TEAMVIEWER=teamviewer-suse.x86_64.rpm
FILENAME_TEAMVIEWER_KEY=TeamViewer2017.asc
rm $FILENAME_TEAMVIEWER $FILENAME_TEAMVEIWER_KEY	
DL_PACKAGE_TEAMVIEWER=https://download.teamviewer.com/download/linux/$FILENAME_TEAMVIEWER
#wget https://download.teamviewer.com/download/linux/signature/$FILENAME_TEAMVIEWER_KEY
keys="$keys\nsudo rpm --import $FILENAME_TEAMVIEWER_KEY"
#wget $DL_PACKAGE_TEAMVIEWER
packages="$packages $FILENAME_TEAMVIEWER"

# Skype
FILENAME_SKYPE=skypeforlinux-64.rpm
FILENAME_SKYPE_KEY=repomd.xml.key
rm $FILENAME_SKYPE $FILENAME_SKYPE_KEY	
DL_PACKAGE_SKYPE=https://go.skype.com/$FILENAME_SKYPE
#wget https://repo.skype.com/rpm/stable/repodata/$FILENAME_SKYPE_KEY
keys="$keys\nsudo rpm --import $FILENAME_SKYPE_KEY"
#wget $DL_PACKAGE_SKYPE
packages="$packages $FILENAME_SKYPE"

# Chrome
FILENAME_CHROME=google-chrome-stable_current_x86_64.rpm
FILENAME_CHROME_KEY=linux_signing_key.pub 
rm $FILENAME_CHROME $FILENAME_CHROME_KEY	
DL_PACKAGE_CHROME=https://dl.google.com/linux/direct/$FILENAME_CHROME
#wget https://dl.google.com/linux/$FILENAME_CHROME_KEY
keys="$keys\nsudo rpm --import $FILENAME_CHROME_KEY"
#wget $DL_PACKAGE_CHROME
packages="$packages $FILENAME_CHROME"

# XnView
# FILENAME_XNVIEW=XnViewMP-linux.x86_64.rpm
# DL_PACKAGE_XNVIEW=http://download.xnview.com/$FILENAME_XNVIEW
# #wget $DL_PACKAGE_XNVIEW
# packages="$packages $FILENAME_XNVIEW"

cd -
echo
echo cd to $temp
echo -e $keys
echo
echo $packages
