#!/bin/bash

# Fish
## Install fish
## if parameter is set
if [ "$1" = "install" ] || [ "$1" = "in" ]; then
	sudo zypper in fish
	chsh -s /usr/bin/fish `whoami`
fi

## Add fzf to fish
./shell-fish-fzf

## Install oh-my-fish
./shell-fish-omf

## omf bang bang
./shell-fish-omf-bb

## Copy promt configuration
cd shell-fish-config
./copy-conf.sh
cd -
