#!/bin/bash

# Fish
## Install fish
sudo zypper in fish
chsh -s /usr/bin/fish `whoami`

## Add fzf to fish
./shell-fish-fzf

## Install oh-my-fish
./shell-fish-omf

## omf bang bang
./shell-fish-omf-bb
