#! /usr/bin/sh

# Fish
## Install oh-my-fish
git clone https://github.com/oh-my-fish/oh-my-fish
cd oh-my-fish
bin/install --offline --path=~/.local/share/omf --config=~/.config/omf

## Reload profile to add omf
source ~/.bash_profile
