#!/bin/bash

GIT_REPO_SPOTIFY=https://github.com/flanaras/opensuse-spotify-installer

# Spotify
# https://github.com/flanaras/opensuse-spotify-installer
git clone $GIT_REPO_SPOTIFY
cd opensuse-spotify-installer
./install-spotify.sh
cd -
rm -rf opensuse-spotify-installer

