#!/bin/bash

#version="Leap_15.0"
#version="Tumbleweed"

fish=https://download.opensuse.org/repositories/shells:/fish/openSUSE_$version/
fonts=http://download.opensuse.org/repositories/M17N:/fonts/openSUSE_$version/
mozilla=http://download.opensuse.org/repositories/mozilla/openSUSE_$version/
packmanessentials=http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_$version/Essentials
x11_utils=https://download.opensuse.org/repositories/X11:Utilities/openSUSE_$version/

if [[ -z $version ]]; then
    string="No openSUSE version provided."
    echo -e "\033[1;31m$string\033[0m"
    echo Exiting.
    exit
fi

# Packman codecs
echo sudo zypper ar -cfp 90 $packmanessentials packman-essentials 
echo sudo zypper dup --from packman-essentials

# Mozilla
echo sudo zypper ar -cfp 90 $mozilla mozilla
echo sudo zypper dup --from mozilla

# Fonts
echo sudo zypper ar -cfp 90 $fonts fonts
echo sudo zypper dup --from fonts

# X11-utils 
echo sudo zypper ar -cfp 90 $x11_utils x11-utils
echo sudo zypper dup --from x11-utils
echo sudo zypper in polybar

# Fish shell
echo sudo zypper ar -cfp 90 $fish shells-fish
echo sudo zypper dup --from shells-fish
echo sudo zypper in fish
