#!/bin/bash

# Music control buttons
packages="playerctl"

# Screenshot
packages="$packages scrot"

# Compositor
packages="$packages compton"

# Background
packages="$packages feh"

# echo packages
echo $packages
