#!/bin/bash

lightversion=1.1.2
light=light-$lightversion

# Light
wget --content-disposition https://github.com/haikarainen/light/archive/$lightversion.tar.gz
tar xf $light.tar.gz

cd $light/
make
sudo bash -c "make install"
cd -

rm $light.tar.gz
