#!/bin/bash

# Music control buttons
packages="playerctl"

# Screenshot
packages="$packages scrot"

# Compositor
packages="$packages compton"

# Background
packages="$packages feh"

# Notifications
packages="$packages dunst"

# Touch pad
packages="$packages xorg-x11-driver-input xf86-input-libinput"

# Battery tray
packages="$packages xfce4-power-manager"

# NetworkManager applet
packages="$packages NetworkManager-applet"

# echo packages
echo $packages
