#!/bin/bash

lightversion=1.2
light=light-$lightversion

# Light
wget --content-disposition https://github.com/haikarainen/light/releases/download/v$lightversion/$light.tar.gz
tar xf $light.tar.gz

cd $light/
./configure
make
sudo bash -c "make install"
cd -

rm $light.tar.gz
