#!/usr/bin/env bash
base=`dirname $0`
source "$base/updater-lib"

name=proton-bridge

response=`curl -s https://protonmail.com/download/current_version_linux.json`
version_remote=`echo $response | jq -r '.Version'`
#version_local=`zypper if protonmail-bridge | rgi version | awk '{print $3}' | sed 's/-.*//'` 
version_local=`rpm -q protonmail-bridge | sed 's/protonmail-bridge-//g' | sed 's/-.*//'` 

printVersionMessage $name $version_local $version_remote

if [ "$version_local" = "$version_remote" ]; then
    echo running latest version
    exit
else
    newVersionAvailable $name $version_local $version_remote

    cd ~/Downloads
    rpmLink=`echo $response | jq -r .RpmFile`
    download $rpmLink
    gnomesu -c "zypper in `basename $rpmLink`"
    rm `basename $rpmLink`
    cd - > /dev/null 2>&1
fi
