#!/usr/bin/env bash
base=`dirname $0`
source "$base/updater-lib"

name=viber

cd `mktemp -d`
rpmLink=https://download.cdn.viber.com/desktop/Linux/viber.rpm
download $rpmLink
version_remote=`rpm -qp \`basename $rpmLink\``

version_local=`rpm -q viber` 

printVersionMessage $name $version_local $version_remote

if [ "$version_local" = "$version_remote" ]; then
    echo running latest version
    exit
else
    newVersionAvailable $name $version_local $version_remote

    gnomesu -c "zypper in `basename $rpmLink`"
    rm `basename $rpmLink`
fi
